#ifndef DISTOPIA_SIMD_CAPABILITY_H
#define DISTOPIA_SIMD_CAPABILITY_H

#ifndef DISTOPIA_SSE1_SUPPORTED
#define DISTOPIA_SSE1_SUPPORTED 0
#endif

#ifndef DISTOPIA_SSE2_SUPPORTED
#define DISTOPIA_SSE2_SUPPORTED 0
#endif

#ifndef DISTOPIA_SSE3_SUPPORTED
#define DISTOPIA_SSE3_SUPPORTED 0
#endif

#ifndef DISTOPIA_SSSE3_SUPPORTED
#define DISTOPIA_SSSE3_SUPPORTED 0
#endif

#ifndef DISTOPIA_SSE4_1_SUPPORTED
#define DISTOPIA_SSE4_1_SUPPORTED 0
#endif

#ifndef DISTOPIA_SSE4_2_SUPPORTED
#define DISTOPIA_SSE4_2_SUPPORTED 0
#endif

#ifndef DISTOPIA_AVX_SUPPORTED
#define DISTOPIA_AVX_SUPPORTED 0
#endif

#ifndef DISTOPIA_AVX2_SUPPORTED
#define DISTOPIA_AVX2_SUPPORTED 0
#endif

#ifndef DISTOPIA_AVX512_SUPPORTED
#define DISTOPIA_AVX512_SUPPORTED 0
#endif


#endif // DISTOPIA_SIMD_CAPABILITY_H