name: Build and upload to PyPI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  release:
    types:
      - published
  pull_request:
    branches:
      - master


concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}"
  cancel-in-progress: true


defaults:
  run:
    shell: bash -l {0}


jobs:
  build_deploy:
    environment: deploy
    if: "github.repository == 'MDAnalysis/distopia'"
    name: Build tarball
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install_deps
        run: |
          python -m pip install build

      - name: build
        run: |
          python -m build --sdist --outdir dist/

      - name: publish_testpypi
        # Upload to testpypi on every tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: publish_pypi
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
