name: Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: distopia
    - uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt

    - name: Build
      shell: bash
      # Execute build 
      run: python3 setup.py install 

    - name: Doxygen
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Path to Doxyfile
        doxyfile-path: "./Doxyfile" # default is ./Doxyfile
        # Working directory
        working-directory: "./docs" # default is .
    

    - name:  Build Sphinx 🔧 # This is built with makefile
      run: |
        pip install sphinx sphinx-sitemap sphinx_rtd_theme breathe
        cd docs
        make html
      
    - name: Deploy 🚀
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/_build/html # The folder the action should deploy.